### ISSUE TITLE
Getting started - Unable to get the code to install and run

### ISSUE THREAD

**Issue by connecteev** [iexcloud/iexjs#110]
**Describe the bug**
Unable to get the code to install and run. Also, how do I run the code examples?

**To Reproduce**
1. Git clone the repo and cd into the folder
$ ls
AUTHORS			CODE_OF_CONDUCT.md	LICENSE			dist			examples		package-lock.json	rollup.config.js	test
CATALOG.md		CONTRIBUTING.md		README.md		docs			node_modules		package.json		src			yarn.lock

2. Run 
```$ yarn build```
```
yarn run v1.22.5
$ npm-run-all -p build:*
$ rollup -c rollup.config.js

src/js/index.js → dist/esm/iexjs.js...
┌────────────────────────────────────┐
│                                    │
│   Destination: dist/esm/iexjs.js   │
│   Bundle Size:  138.51 KB          │
│   Minified Size:  138.5 KB         │
│   Gzipped Size:  31.99 KB          │
│                                    │
└────────────────────────────────────┘
created dist/esm/iexjs.js in 14.3s

src/js/index.js → dist/cjs/iexjs.js...
(!) Plugin inject: rollup-plugin-inject: failed to parse /Users/kunalpunjabi/Code/EXPLORATIONS/STOCKS/iexcloud/iexjs/package.json. Consider restricting the plugin to particular files via options.include
package.json
created dist/cjs/iexjs.js in 7s
✨  Done in 24.13s.
```

**Expected behavior**
The build to be successful. 

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser N/A - console

Also, how do I run the code examples?

**Comment by timkpaine** [comment]
you ran `yarn` before `yarn build` right?

**Comment by timkpaine** [comment]
looks like this happens in `CI` as well, might be a plugin problem:
https://github.com/iexcloud/iexjs/runs/3237147598?check_suite_focus=true

**Comment by timkpaine** [comment]
(note that it doesnt actually effect the build, its just a warning)

**Comment by connecteev** [comment]
@timkpaine thank you for the quick response, ```yarn && yarn build ``` worked. Still not sure how to get the code running from either CLI or browser

**Comment by timkpaine** [comment]
Create a new application for node or browse, npm or yarn install iexjs, and then follow along with any of the examples or the README code.
