### ISSUE TITLE
Fill in typings

### ISSUE THREAD

**Issue by timkpaine** [iexcloud/iexjs#23]
Fill in typings

**Comment by ablankenship10** [comment]
My bad this is a duplicate, at the very least the index.d.ts file should be removed from the published build until it is complete as it prevents any IDE discovery of types from the code itself which is at least fairly if not completely usable as is if you delete the file manually.

**Comment by timpaine-iex** [comment]
sure, I had planned on doing them right away but never got around to it

**Comment by timkpaine** [comment]
going to close this for now, i'll get to the typings eventually
