### ISSUE TITLE
SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by DushanMinic** [iexcloud/iexjs#31]
**Describe the bug**
Getting the error from the title when I try the example from the readme.

**To Reproduce**
```javascript
const { Client } = require('iexjs');

const client = new Client({ token: 'sandbox_client_key', version: 'sandbox' });

client.chart('AAPL', '1m').then((res) => {
	console.log(res);
});
```

**Expected behavior**
Expecting to get the AAPL chart data.

**Screenshots**
<img width="843" alt="Screen Shot 2021-03-29 at 3 53 45 PM" src="https://user-images.githubusercontent.com/12270056/112847121-099aa500-90a7-11eb-8356-18545f4e0346.png">

**Additional context**
Node version: 12.9.0
"iexjs": "^0.2.4"

**Comment by timpaine-iex** [comment]
You're using the `esm` version where you probably wanted the `cjs` version if you're running in node.

**Comment by DushanMinic** [comment]
I see that you've got cjs/esm folders. Is there a way to make sure the library uses cjs version?

**Comment by timpaine-iex** [comment]
For now just do `const { Client } = require('iexjs/dist/cjs/iexjs');`. I'll remap the main so it points to the commonjs version (I've been using this mostly for browser based code so far so the `node` side might have some slight rough edges here and there).

**Comment by DushanMinic** [comment]
I see, thanks for the fast response - I seem to be getting the result from IEX API now. 🥳
