### ISSUE TITLE
 ERROR  Error: API Token missing or not in environment (IEX_TOKEN)

### ISSUE THREAD

**Issue by minuitagency** [iexcloud/iexjs#33]
Hi, 

Thanks for the library, using it in our React Native app,

we have an issue when using the library this way: 

```
    const client = new Client({
      token: 'sandbox publishable token here',
      version: 'sandbox',
    });

    client.cryptoQuotesSSE('BTCUSD', (e) => {
      console.log(e);
    });
```

The error is: 

` ERROR  Error: API Token missing or not in environment (IEX_TOKEN)
`
But it works when using the example from the readme (with chart).

Any idea? 

Thanks, 

Théo

**Comment by timpaine-iex** [comment]
I do this all the time too, so maybe I'll add in support for either but right now its `api_token` not `token`:
https://github.com/iexcloud/iexjs/blob/main/src/js/client.js#L15

This is just a carryover from `pyEX`: https://github.com/iexcloud/pyEX/blob/main/pyEX/client.py#L1624
