### ISSUE TITLE
Some fundamentals return empty arrays

### ISSUE THREAD

**Issue by illoRocks** [iexcloud/iexjs#66]
Hi,
the function below always returns an empty array, because the left-hand side of OR is always undefined.

https://github.com/iexcloud/iexjs/blob/e491c644596b25e7a56740361dce62407f0a54a6/src/js/stocks/fundamentals.js#L43-L51

The problem could be a misplaced bracket. It should look like this:
```js
(await _get({...})).balancesheet || []
```
Besides this problem the result of the different functions are inconsistent. Sometimes it returns a promise and sometimes not. In my opinion, it should always return a promise. So the user has to handle the raw result from iex and extract the property

**Comment by markwindsorr** [comment]
same issue, seems like theres an unneeded slash when theres more parameters in the endpoint

**Comment by timkpaine** [comment]
Yeah it's a misplaced paren, good catch. Keep in mind that you can (and generally should) query this data through time series.

**Comment by markwindsorr** [comment]
Im getting this error `{"error":"child \"last\" fails because [\"last\" must be a number]"}` ... Endpoint._url looks like `https://cloud.iexapis.com/v1/stock/AAPL/balance-sheet?period=quarter&last=1/` in urls.js and it will work if I remove that ending back slash
