### ISSUE TITLE
Implement or remove blank index.d.ts file for IDE autocomplete

### ISSUE THREAD

**Issue by ablankenship10** [iexcloud/iexjs#69]
**Describe the bug**
There is currently a blank index.d.ts file in this project. It should be implemented correctly as the blank declaration disrupts default IDE discovery of types via the code.

**To Reproduce**
1. Import iexjs and notice no autocomplete of exported variables or functions available to initialized Client objects.
2. Goto node_modules/iexjs and delete index.d.ts
3. In VS Code, decent autocomplete is available again.

**Expected behavior**
The typings should be implemented or file removed for proper type discovery.

**Comment by timkpaine** [comment]
Dupe https://github.com/iexcloud/iexjs/issues/23
